// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  /**
   * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
   */
  interface GetMessageOptions {
    /**
     * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
     */
    escapeLt?: boolean
  }

  export interface WxtI18n extends I18n.Static {
    /**
     * The extension or app ID; you might use this string to construct URLs for resources inside the extension. Even unlocalized extensions can use this message.
     * Note: You can't use this message in a manifest file.
     *
     * "<browser.runtime.id>"
     */
    getMessage(
      messageName: "@@extension_id",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "<browser.i18n.getUiLocale()>"
     */
    getMessage(
      messageName: "@@ui_locale",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The text direction for the current locale, either "ltr" for left-to-right languages such as English or "rtl" for right-to-left languages such as Japanese.
     *
     * "<ltr|rtl>"
     */
    getMessage(
      messageName: "@@bidi_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "rtl"; otherwise, it's "ltr".
     *
     * "<rtl|ltr>"
     */
    getMessage(
      messageName: "@@bidi_reversed_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "left"; otherwise, it's "right".
     *
     * "<left|right>"
     */
    getMessage(
      messageName: "@@bidi_start_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "right"; otherwise, it's "left".
     *
     * "<right|left>"
     */
    getMessage(
      messageName: "@@bidi_end_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "AcFun助手"
     */
    getMessage(
      messageName: "appName",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "AcFun助手"
     */
    getMessage(
      messageName: "appDesc",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "AcFun助手"
     */
    getMessage(
      messageName: "optTitle",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "进入主站"
     */
    getMessage(
      messageName: "omniboxDefaultSuggestion",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "查看 $KEYWORD$ 在主站的有关内容"
     */
    getMessage(
      messageName: "omniboxInputSuggestion",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "上次更新到 $LASTVIDEO$"
     */
    getMessage(
      messageName: "bangumiUpdateNotifyItemDetailMessage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "概览"
     */
    getMessage(
      messageName: "bangumiUpdateNotifyItemOverviewTitle",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "今天有 $LEN$ 个番剧更新。"
     */
    getMessage(
      messageName: "bangumiUpdateNotifyItemOverviewMessage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "AcFun 助手 - 番剧更新提示"
     */
    getMessage(
      messageName: "bangumiUpdateNotifyTitle",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "今天大概有 $LEN$ 个番剧更新。"
     */
    getMessage(
      messageName: "bangumiUpdateNotifyMessage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "助手-我的番剧"
     */
    getMessage(
      messageName: "bangumiUpdateNotifyBtn0",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "主站-番剧"
     */
    getMessage(
      messageName: "bangumiUpdateNotifyBtn1",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    getMessage(
      messageName: "@@extension_id" | "@@ui_locale" | "@@bidi_dir" | "@@bidi_reversed_dir" | "@@bidi_start_edge" | "@@bidi_end_edge" | "appName" | "appDesc" | "optTitle" | "omniboxDefaultSuggestion" | "omniboxInputSuggestion" | "bangumiUpdateNotifyItemDetailMessage" | "bangumiUpdateNotifyItemOverviewTitle" | "bangumiUpdateNotifyItemOverviewMessage" | "bangumiUpdateNotifyTitle" | "bangumiUpdateNotifyMessage" | "bangumiUpdateNotifyBtn0" | "bangumiUpdateNotifyBtn1",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
  }
}
