// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/Image/404img.png"
    | "/Scss/globalVar.scss"
    | "/Svg/Settings32Filled.svg"
    | "/_locales/en/messages.json"
    | "/_locales/zh_CN/messages.json"
    | "/_locales/zh_TW/messages.json"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/icon128.png"
    | "/icon/icon16.png"
    | "/icon/icon32.png"
    | "/icon/icon48.png"
    | "/icon/icon64.png"
    | "/options.html"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
