// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    NCard: typeof import("naive-ui")["NCard"];
    NColorPicker: typeof import("naive-ui")["NColorPicker"];
    NConfigProvider: typeof import("naive-ui")["NConfigProvider"];
    NDataTable: typeof import("naive-ui")["NDataTable"];
    NDialogProvider: typeof import("naive-ui")["NDialogProvider"];
    NEl: typeof import("naive-ui")["NEl"];
    NForm: typeof import("naive-ui")["NForm"];
    NFormItem: typeof import("naive-ui")["NFormItem"];
    NInput: typeof import("naive-ui")["NInput"];
    NMessageProvider: typeof import("naive-ui")["NMessageProvider"];
    NModal: typeof import("naive-ui")["NModal"];
    NTime: typeof import("naive-ui")["NTime"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
