enum avaliableVideoQuality {
  "2160P120HDR" = "2160p120HDR",
  "2160P120" = "2160p120",
  "2160P60HDR" = "2160p60HDR",
  "2160P60" = "2160p60",
  "2160PHDR" = "2160pHDR",
  "2160P" = "2160p",
  "1080P60HDR" = "1080p60HDR",
  "1080P60" = "1080p60",
  "1080P+" = "1080p+",
  "1080PHDR" = "1080pHDR",
  "1080P" = "1080p",
  "720P60" = "720p60",
  "720P" = "720p",
  "540P" = "540p",
  "480P" = "480p",
  "360P" = "360p",
}

interface videoQualitiesType {
  definition?: string;
  disableAutoSwitch?: boolean;
  limitType?: number;
  qualityLabel: string;
  qualityType: string;
  width: number;
  height: number;
  defaultSelect?: boolean;
}

const videoQualitiesRefer: Record<string, videoQualitiesType> = {
  "2160p120HDR": {
    definition: "4K",
    disableAutoSwitch: true,
    limitType: 1,
    qualityLabel: "2160P120 HDR",
    qualityType: "2160p120HDR",
    width: 3840,
    height: 2160,
  },
  "2160p120": {
    limitType: 1,
    disableAutoSwitch: true,
    qualityType: "2160p120",
    qualityLabel: "2160P120",
    definition: "4K",
    width: 3840,
    height: 2160,
  },
  "2160p60HDR": {
    limitType: 1,
    disableAutoSwitch: true,
    qualityType: "2160p60HDR",
    qualityLabel: "2160P60 HDR",
    definition: "4K",
    width: 3840,
    height: 2160,
  },
  "2160p60": {
    limitType: 1,
    disableAutoSwitch: true,
    qualityType: "2160p60",
    qualityLabel: "2160P60",
    definition: "4K",
    width: 3840,
    height: 2160,
  },
  "2160pHDR": {
    limitType: 1,
    disableAutoSwitch: true,
    qualityType: "2160pHDR",
    qualityLabel: "2160P HDR",
    definition: "4K",
    width: 3840,
    height: 2160,
  },
  "2160p": {
    limitType: 1,
    disableAutoSwitch: true,
    qualityType: "2160p",
    qualityLabel: "2160P",
    definition: "4K",
    width: 3840,
    height: 2160,
  },
  "1080p60HDR": {
    limitType: 1,
    qualityType: "1080p60HDR",
    qualityLabel: "1080P60 HDR",
    definition: "HD",
    width: 1920,
    height: 1080,
  },
  "1080p60": {
    limitType: 1,
    qualityType: "1080p60",
    qualityLabel: "1080P60",
    definition: "HD",
    width: 1920,
    height: 1080,
  },
  "1080p+": {
    limitType: 1,
    qualityType: "1080p+",
    qualityLabel: "1080P+",
    definition: "HD",
    width: 1920,
    height: 1080,
  },
  "1080pHDR": {
    limitType: 1,
    qualityType: "1080pHDR",
    qualityLabel: "1080P HDR",
    definition: "HD",
    width: 1920,
    height: 1080,
  },
  "1080p": {
    limitType: 1,
    qualityType: "1080p",
    qualityLabel: "1080P",
    definition: "HD",
    width: 1920,
    height: 1080,
  },
  "720p60": {
    limitType: 1,
    qualityType: "720p60",
    qualityLabel: "720P60",
    width: 1280,
    height: 720,
  },
  "720p": {
    defaultSelect: true,
    qualityType: "720p",
    qualityLabel: "720P",
    width: 1280,
    height: 720,
  },
  "540p": {
    qualityType: "540p",
    qualityLabel: "540P",
    width: 960,
    height: 540,
  },
  "480p": {
    qualityType: "480p",
    qualityLabel: "480P",
    width: 720,
    height: 480,
  },
  "360p": {
    qualityType: "360p",
    qualityLabel: "360P",
    width: 640,
    height: 360,
  },
};

/**
 * 每一千秒所播放的帧数
 * @refer @伯翎飞云[2021年4月8日21:31:47]："电影23.976;60帧如果是NTSC的话是59.94;感知不强方向错了"
 */
const standardFrameRate: Record<string, number> = {
  "24": 23976,
  "25": 25000,
  "30": 29970,
  "60": 59940,
  "120": 120000
}

const navigators = [
  {
    "id": 105,
    "navName": "番剧",
    "parent": 0,
    "link": "/bangumilist",
    "status": 0,
    "mediaType": 0,
    "cid": 155,
    "orders": 100,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 131,
        "navName": "番剧列表",
        "parent": 105,
        "link": "/bangumilist",
        "status": 0,
        "mediaType": 0,
        "cid": 0,
        "orders": 60,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 115,
        "navName": "TV动画",
        "parent": 105,
        "link": "/v/list67/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 67,
        "orders": 50,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 116,
        "navName": "剧场动画",
        "parent": 105,
        "link": "/v/list180/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 180,
        "orders": 40,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 130,
        "navName": "国产动画",
        "parent": 105,
        "link": "/v/list120/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 120,
        "orders": 30,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 14,
    "navName": "动画",
    "parent": 0,
    "link": "/v/list1/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 1,
    "orders": 90,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 132,
        "navName": "动画综合",
        "parent": 14,
        "link": "/v/list106/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 106,
        "orders": 70,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 133,
        "navName": "短片·手书·配音",
        "parent": 14,
        "link": "/v/list190/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 190,
        "orders": 60,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 34,
        "navName": "MAD·AMV",
        "parent": 14,
        "link": "/v/list107/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 107,
        "orders": 50,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 35,
        "navName": "MMD·3D",
        "parent": 14,
        "link": "/v/list108/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 108,
        "orders": 40,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 157,
        "navName": "虚拟偶像",
        "parent": 14,
        "link": "/v/list207/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 207,
        "orders": 35,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 41,
        "navName": "动画资讯",
        "parent": 14,
        "link": "/v/list159/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 159,
        "orders": 30,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 36,
        "navName": "COSPLAY·声优",
        "parent": 14,
        "link": "/v/list133/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 133,
        "orders": 20,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 97,
        "navName": "特摄",
        "parent": 14,
        "link": "/v/list99/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 99,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 162,
        "navName": "番剧二创",
        "parent": 14,
        "link": "/v/list212/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 212,
        "orders": 5,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 18,
    "navName": "娱乐",
    "parent": 0,
    "link": "/v/list60/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 60,
    "orders": 87,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 156,
        "navName": "搞笑",
        "parent": 18,
        "link": "/v/list206/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 206,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 68,
        "navName": "鬼畜",
        "parent": 18,
        "link": "/v/list87/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 87,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 128,
        "navName": "明星",
        "parent": 18,
        "link": "/v/list188/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 188,
        "orders": 9,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 153,
    "navName": "生活",
    "parent": 0,
    "link": "/v/list201/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 201,
    "orders": 86,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 69,
        "navName": "生活日常",
        "parent": 153,
        "link": "/v/list86/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 86,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 66,
        "navName": "萌宠",
        "parent": 153,
        "link": "/v/list88/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 88,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 65,
        "navName": "美食",
        "parent": 153,
        "link": "/v/list89/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 89,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 154,
        "navName": "旅行",
        "parent": 153,
        "link": "/v/list204/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 204,
        "orders": 2,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 85,
        "navName": "手工·绘画",
        "parent": 153,
        "link": "/v/list127/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 127,
        "orders": 2,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 155,
        "navName": "美妆·造型",
        "parent": 153,
        "link": "/v/list205/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 205,
        "orders": 1,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 16,
    "navName": "音乐",
    "parent": 0,
    "link": "/v/list58/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 58,
    "orders": 80,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 166,
        "navName": "治愈系",
        "parent": 16,
        "link": "/v/list215/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 215,
        "orders": 100,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 57,
        "navName": "原创·翻唱",
        "parent": 16,
        "link": "/v/list136/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 136,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 55,
        "navName": "演奏·乐器",
        "parent": 16,
        "link": "/v/list137/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 137,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 54,
        "navName": "Vocaloid",
        "parent": 16,
        "link": "/v/list103/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 103,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 52,
        "navName": "综合音乐",
        "parent": 16,
        "link": "/v/list139/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 139,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 129,
        "navName": "音乐选集·电台",
        "parent": 16,
        "link": "/v/list185/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 185,
        "orders": 9,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 17,
    "navName": "舞蹈·偶像",
    "parent": 0,
    "link": "/v/list123/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 123,
    "orders": 75,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 63,
        "navName": "宅舞",
        "parent": 17,
        "link": "/v/list134/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 134,
        "orders": 5,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 59,
        "navName": "综合舞蹈",
        "parent": 17,
        "link": "/v/list135/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 135,
        "orders": 4,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 81,
        "navName": "偶像",
        "parent": 17,
        "link": "/v/list129/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 129,
        "orders": 3,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 159,
        "navName": "中国舞",
        "parent": 17,
        "link": "/v/list208/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 208,
        "orders": 1,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 15,
    "navName": "游戏",
    "parent": 0,
    "link": "/v/list59/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 59,
    "orders": 74,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 165,
        "navName": "王者荣耀",
        "parent": 15,
        "link": "/v/list214/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 214,
        "orders": 40,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 161,
        "navName": "我的世界",
        "parent": 15,
        "link": "/v/list210/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 210,
        "orders": 40,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 167,
        "navName": "和平精英",
        "parent": 15,
        "link": "/v/list216/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 216,
        "orders": 35,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 168,
        "navName": "第五人格",
        "parent": 15,
        "link": "/v/list217/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 217,
        "orders": 20,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 44,
        "navName": "英雄联盟",
        "parent": 15,
        "link": "/v/list85/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 85,
        "orders": 20,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 47,
        "navName": "电子竞技",
        "parent": 15,
        "link": "/v/list145/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 145,
        "orders": 19,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 134,
        "navName": "网络游戏",
        "parent": 15,
        "link": "/v/list186/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 186,
        "orders": 17,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 45,
        "navName": "主机单机",
        "parent": 15,
        "link": "/v/list84/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 84,
        "orders": 16,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 135,
        "navName": "手机游戏",
        "parent": 15,
        "link": "/v/list187/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 187,
        "orders": 12,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 43,
        "navName": "桌游卡牌",
        "parent": 15,
        "link": "/v/list165/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 165,
        "orders": 8,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 19,
    "navName": "科技",
    "parent": 0,
    "link": "/v/list70/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 70,
    "orders": 65,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 160,
        "navName": "手办模玩",
        "parent": 19,
        "link": "/v/list209/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 209,
        "orders": 8,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 71,
        "navName": "科技制造",
        "parent": 19,
        "link": "/v/list90/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 90,
        "orders": 6,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 136,
        "navName": "人文科普",
        "parent": 19,
        "link": "/v/list189/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 189,
        "orders": 5,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 70,
        "navName": "汽车",
        "parent": 19,
        "link": "/v/list122/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 122,
        "orders": 3,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 84,
        "navName": "数码家电",
        "parent": 19,
        "link": "/v/list91/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 91,
        "orders": 2,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 73,
        "navName": "演讲·公开课",
        "parent": 19,
        "link": "/v/list151/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 151,
        "orders": 2,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 82,
        "navName": "广告",
        "parent": 19,
        "link": "/v/list149/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 149,
        "orders": 1,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 20,
    "navName": "影视",
    "parent": 0,
    "link": "/v/list68/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 68,
    "orders": 60,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 170,
        "navName": "影视混剪",
        "parent": 20,
        "link": "/v/list219/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 219,
        "orders": 100,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 137,
        "navName": "预告·花絮",
        "parent": 20,
        "link": "/v/list192/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 192,
        "orders": 100,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 138,
        "navName": "电影杂谈",
        "parent": 20,
        "link": "/v/list193/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 193,
        "orders": 90,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 139,
        "navName": "追剧社",
        "parent": 20,
        "link": "/v/list194/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 194,
        "orders": 85,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 140,
        "navName": "综艺show",
        "parent": 20,
        "link": "/v/list195/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 195,
        "orders": 80,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 141,
        "navName": "纪录片·短片",
        "parent": 20,
        "link": "/v/list196/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 196,
        "orders": 75,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 21,
    "navName": "体育",
    "parent": 0,
    "link": "/v/list69/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 69,
    "orders": 55,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 93,
        "navName": "综合体育",
        "parent": 21,
        "link": "/v/list152/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 152,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 92,
        "navName": "足球",
        "parent": 21,
        "link": "/v/list94/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 94,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 91,
        "navName": "篮球",
        "parent": 21,
        "link": "/v/list95/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 95,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 90,
        "navName": "搏击健身",
        "parent": 21,
        "link": "/v/list153/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 153,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 87,
        "navName": "极限竞速",
        "parent": 21,
        "link": "/v/list93/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 93,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 22,
    "navName": "鱼塘",
    "parent": 0,
    "link": "/v/list125/index.htm",
    "status": 0,
    "mediaType": 0,
    "cid": 125,
    "orders": 45,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 118,
        "navName": "普法安全",
        "parent": 22,
        "link": "/v/list183/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 183,
        "orders": 11,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 78,
        "navName": "国防军事",
        "parent": 22,
        "link": "/v/list92/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 92,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 72,
        "navName": "历史",
        "parent": 22,
        "link": "/v/list131/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 131,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 67,
        "navName": "新鲜事·正能量",
        "parent": 22,
        "link": "/v/list132/index.htm",
        "status": 0,
        "mediaType": 0,
        "cid": 132,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  },
  {
    "id": 24,
    "navName": "文章",
    "parent": 0,
    "link": "/v/list63/index.htm",
    "status": 0,
    "mediaType": 1,
    "cid": 63,
    "orders": 40,
    "navGrade": 0,
    "todayContentsCount": 0,
    "cmsCanSelect": 0,
    "children": [
      {
        "id": 119,
        "navName": "动漫",
        "parent": 24,
        "link": "/v/list184/index.htm",
        "status": 0,
        "mediaType": 1,
        "cid": 184,
        "orders": 11,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 26,
        "navName": "资讯",
        "parent": 24,
        "link": "/v/list110/index.htm",
        "status": 0,
        "mediaType": 1,
        "cid": 110,
        "orders": 10,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 27,
        "navName": "生活",
        "parent": 24,
        "link": "/v/list73/index.htm",
        "status": 0,
        "mediaType": 1,
        "cid": 73,
        "orders": 6,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 32,
        "navName": "游戏",
        "parent": 24,
        "link": "/v/list164/index.htm",
        "status": 0,
        "mediaType": 1,
        "cid": 164,
        "orders": 4,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      },
      {
        "id": 172,
        "navName": "广而告之",
        "parent": 24,
        "link": "/v/list76/index.htm",
        "status": 0,
        "mediaType": 1,
        "cid": 76,
        "orders": 1,
        "navGrade": 0,
        "todayContentsCount": 0,
        "cmsCanSelect": 0,
        "children": []
      }
    ]
  }
]

export const Encylopedia = {
  standardFrameRate,
  avaliableVideoQuality,
  videoQualitiesRefer,
  navigators,
};
