name: Publish (legacy)
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publishRelease:
    name: publish a release package
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@main

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: "zip"
        run: pnpx wxt zip

      - name: "publish"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "develop"
          prerelease: false
          draft: false
          files: |
            .output/*.zip